controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - virtual_joint
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses per group
  - group: robot_arm
    pose: ready